### ISSUE TITLE
Can you please describe your Obsidian environment ? 

### ISSUE THREAD

**Issue by kovalroma** [mr-karan/notes#1]
Hello, and thank you for showing your notes. 
I'm curious about what Obsidian config you are using. Can you show your `.obsidian` folder? 

How do you work with special tags, like ` ```bash ` or `!!! tip ` or similar?  Is there any plugin for writing this block more easily? 

I would appreciate it if you describe your Obsidian environment.

**Comment by mr-karan** [comment]
Hey. I've kept things really simple in this Vault. No external plugins or tags. Just a bunch of markdown files. Code blocks are written like how they're written in normal Markdown.
